services:

  ai4buzz:
    #build: .
    image: ai4buzz-imgs:latest
    container_name: ai4buzz-imgs
    restart: always
    volumes:
      - ./api:/app/api
      #- ./nltk_data:/root/nltk_data
    ports:
      - "80:80"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    command:
      bash -c "uvicorn api.main:app --host 0.0.0.0 --port 80"
      #bash -c "gunicorn api.main:app --workers 1 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:80"
    #environment:
    #  - PORT=80
    #  - TIMEOUT=500
      #- BIND=0.0.0.0:81
      #- WORKERS_PER_CORE=0.5
      #- MAX_WORKERS=5
